### ISSUE TITLE
Would be nice with pod support

### ISSUE THREAD

**Issue by advatar** [textileio/ios-textile#2]

**Comment by asutula** [comment]
Yes, definitely. I'm working on that currently. Trying to research and decide what the best approach is for static library vs dynamic framework, and how to best deal with our dependencies (the generated-from-go-code `Mobile.framework` and Google protobuf runtime). I'll keep you posted on progress here.

**Comment by advatar** [comment]
I tried to do it myself and it is a bit tricky. Carthage is probably easier to begin with.

**Comment by asutula** [comment]
Ok @advatar, wish granted: 

https://cocoapods.org/pods/Textile

The source for the Pod is this repo.
