### ISSUE TITLE
RequestHandler tweaks

### ISSUE THREAD

**Issue by sanderpick** [textileio/ios-textile#58]
@asutula on iOS while switching cafes on an account w/ lots of data, I've seen a requests pile-up that never resolves. Just endless "pending" states. I think a couple things are happening:

1. Here https://github.com/textileio/ios-textile/blob/master/Textile/Classes/RequestsHandler.m#L57, you should request a batch size, not `-1` for all. On android I have that set to 16. Subsequent flush calls will kick off more since this endpoint only returns "new" requests. As an enhancement, when the native-side queue is empty, you could call flush again to kick off another batch. Android could do w/ that change as well.
2. It doesn't look like this error is being checked: https://github.com/textileio/ios-textile/blob/master/Textile/Classes/RequestsHandler.m#L77. There could be an error there like, "no session found for cafe". On Android, I just mark the request as not pending in this case, but that's not right either. We should just fail it, otherwise a bunch of requests will pile up like this.

**Comment by sanderpick** [comment]
(I'll get to work on the android tweak here in a bit)

**Comment by asutula** [comment]
Nice, good ideas. We can do that.
