### ISSUE TITLE
[Textile.instance.cafes register] returns an error "invalid character '<' looking for beginning of value"

### ISSUE THREAD

**Issue by hakumai-iida** [textileio/ios-textile#94]
Hello everybody,
I made a textile project "my_storage" and a token, then tried the sample.

```objc
NSString* gateway = @"https://my_storage.textile.cafe";
NSString* token = @"eefac334-5db8-4392-b5f2-5f6e8e0cb68f";

[Textile.instance.cafes register:gateway token:token completion:^(NSError * _Nonnull error) {
      if (error) {
          NSLog(@"@ registering cafe: error: %@", error.localizedDescription);
      }
    }];
```

 But I got an error with [Textile.instance.cafes register].
> @ registering cafe: error: invalid character '<' looking for beginning of value

Is this a bad textile project setting?
Or does this ios sample not work anymore, because of "Textile Threads v1 are being deprecated".

If you know any information, please let me know

Best regards,

**Comment by carsonfarmer** [comment]
Hi @hakumai-iida, this library has been depreciated in favor of threads v2 tooling. So that sample is no longer working. Please stay tuned to https://blog.textile.io for updates about new mobile SKDs for iOS and Android.

**Comment by andrewxhill** [comment]
or if you'd like to share use-case information or requirements, you could leave any details here https://github.com/textileio/go-threads/issues/60 (which is unscheduled)

**Comment by hakumai-iida** [comment]
@carsonfarmer
@andrewxhill 

Thank you for your replies

I look forward to textileio/go-threads mobile compatibility.
It seems that android version is under development for textileio/go-threads.
I can not wait for iOS.

Thank you very much for kindly telling me.

Best regards,
